// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxcgMmLvg0EX3b82CIYLFm2E9gBJIifRQ',
    appId: '1:761445669025:web:d71ce20df9ece63f2d38e0',
    messagingSenderId: '761445669025',
    projectId: 'crickpulse-843a5',
    authDomain: 'crickpulse-843a5.firebaseapp.com',
    storageBucket: 'crickpulse-843a5.firebasestorage.app',
    measurementId: 'G-276Y1X29DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlVDhwqZF4e_nRa5Hf3eKJd8xH32_ieOw',
    appId: '1:761445669025:android:28ca811a475fe2e52d38e0',
    messagingSenderId: '761445669025',
    projectId: 'crickpulse-843a5',
    storageBucket: 'crickpulse-843a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUNGtg5vgnSSbO2iJ0wKnoTxb0xmZ1k5U',
    appId: '1:761445669025:ios:6cf9956ca52844362d38e0',
    messagingSenderId: '761445669025',
    projectId: 'crickpulse-843a5',
    storageBucket: 'crickpulse-843a5.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUNGtg5vgnSSbO2iJ0wKnoTxb0xmZ1k5U',
    appId: '1:761445669025:ios:6cf9956ca52844362d38e0',
    messagingSenderId: '761445669025',
    projectId: 'crickpulse-843a5',
    storageBucket: 'crickpulse-843a5.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxcgMmLvg0EX3b82CIYLFm2E9gBJIifRQ',
    appId: '1:761445669025:web:60a6487bffc850f12d38e0',
    messagingSenderId: '761445669025',
    projectId: 'crickpulse-843a5',
    authDomain: 'crickpulse-843a5.firebaseapp.com',
    storageBucket: 'crickpulse-843a5.firebasestorage.app',
    measurementId: 'G-VTG2BTL6KW',
  );
}
