import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

// Screens
import 'screens/login_page.dart';
import 'screens/home_page.dart';
import 'screens/score_page.dart';
import 'screens/profile_page.dart';
import 'screens/match_detail_page.dart';
import 'screens/match_list_page.dart';
// import 'screens/teams_page.dart';
// import 'screens/team_detail_page..dart';

// Models
import 'models/match_model.dart'; // Optional if you have it

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(CrickApp());
}

class CrickApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CrickPulse',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.blue),
      home: LoginPage(),
      routes: {
        '/home': (context) => HomePage(username: "User"),
        '/score': (context) => ScorePage(type: "live"),
        '/profile': (context) => ProfilePage(username: "User"),
        '/matchList': (context) => MatchListPage(),
        '/matchDetail': (context) {
          final args = ModalRoute.of(context)!.settings.arguments as MatchModel;
          return MatchDetailPage(matchData: args.toJson());
        },
      },
    );
  }
}